config/routes.rb
MusicApp::Application.routes.draw do

  resources :users
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums do
    resources :tracks, only: [:new]
  end

  resources :tracks do
    resources :notes, only: [:new, :create]
  end

  resources :notes, only: [:destroy]
  root to: redirect('/users')

end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :title, presence: true

  has_many(
    :tracks,
    :class_name => 'Track',
    :foreign_key => :album_id,
    :primary_key => :id,
    dependent: :destroy
  )

  belongs_to(
    :band,
    :class_name => 'Band',
    :foreign_key => :band_id,
    :primary_key => :id
  )
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :band_name, presence: true

  has_many(
    :albums,
    :class_name => 'Album',
    :foreign_key => :band_id,
    :primary_key => :id,
    dependent: :destroy
  )

end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :user_id, :track_id, presence: true

  belongs_to(
    :author,
    :class_name => 'User',
    :foreign_key => :user_id,
    :primary_key => :id
  )

  belongs_to(
    :track,
    :class_name => 'Track',
    :foreign_key => :track_id,
    :primary_key => :id
  )

end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :song_name, presence: true

  after_initialize do
    self.lyrics ||= "No lyrics posted"
  end

  belongs_to(
    :album,
    :class_name => 'Album',
    :foreign_key => :album_id,
    :primary_key => :id
    )

    has_many(
    :notes,
    :class_name => 'Note',
    :foreign_key => :track_id,
    :primary_key => :id,
    dependent: :destroy
    )

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, :password_digest, :presence => true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  has_many(
  :notes,
  :class_name => 'Note',
  :foreign_key => :user_id,
  :primary_key => :id,
  dependent: :destroy
  )

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
   BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def generate_session_token## not finalized
    rand(10000).to_s
  end

  def reset_token
    self.session_token = self.generate_session_token
    self.save!
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      return user
    else
      return nil
    end
  end


end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action do
    redirect_to new_session_url if !logged_in?
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @bands = Band.all
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save!
      redirect_to band_url(params[:album][:band_id])
    else
      render :new
    end
  end

  private
  def album_params
    params[:album].permit(:title, :band_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?


  def login(user)
    user.reset_token
    user.save!
    session[:session] = user.session_token
  end

  def current_user
    return nil if session[:session] == nil
    @current_user ||= User.find_by(session_token: session[:session])
  end

  def logged_in?
    !!current_user
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  before_action do
    redirect_to new_session_url if !self.logged_in?
  end


  def index
    @user = self.current_user if current_user
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_name: params[:band][:band_name])
    if @band.save
      redirect_to bands_url
    else
      render :new
    end
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController


  def create
    @track_id = params[:track_id]
    @note = Note.new(title: params[:note][:title], body: params[:note][:body],
                        track_id: @track_id, user_id: current_user.id)
    @note.save!
    redirect_to track_url(@track_id)

  end

  def destroy
    @note = Note.find_by(id: params[:id])
    track_id = @note.track.id
    @note.destroy if @note
    redirect_to track_url(track_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @msg = ""
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:session][:email], params[:session][:password])
    if @user
      login(@user)
      redirect_to user_url(@user.id)
    else
      @msg = "The log in information given was wrong!!"
      render :new
    end
  end

  def destroy
    user = User.find_by(session_token: session[:session])
    session[:session] = nil
    if user
      user.session_token = nil
      user.save!
    end
    redirect_to users_url
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action do
    redirect_to new_session_url if !logged_in?
  end

  def show
    @user = self.current_user
    @track = Track.find_by(id: params[:id])
    render :show
  end

  def edit
    @track = Track.find_by(id: params[:id])
    render :edit
  end

  def update
    @track = Track.find_by(id: params[:id])
    @track.update!(lyrics: params[:track][:lyrics])
    redirect_to track_url(params[:id])
  end

  def new
    @albums = Album.all
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to album_url(params[:track][:album_id])
    else
      render :new
    end
  end

  private
  def track_params
    params[:track].permit(:song_name, :album_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @current = self.current_user if self.current_user
    @users = User.all
    render :index
  end

  def new
    session[:session] = nil
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end


  private
  def user_params
    params[:user].permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/new.html.erb
<h1>Add an Album!!!!</h1>

<%=@album.errors.full_messages if @album%>

<form action="<%=albums_url%>" method="POST">

  <label for="name"> Album Title</label>
  <input type="text" name="album[title]" id="name">
  <br>
  Choose Band:
  <select name="album[band_id]">

    <% @bands.each do |band| %>
      <option value="<%=band.id%>"><%=band.band_name%></option>
    <%end%>

  </select>

  <button>Submit!</button>

</form>

<br>

<a href="<%=user_url(current_user.id)%>">Back</a>

app/views/albums/show.html.erb
<h1>Album name: <%=@album.title%></h1>

Tracks: <br>
<ul>
  <% @album.tracks.each do |song| %>
    <li> <a href="<%=track_url(song.id)%>"><%=song.song_name%></a> </li><br>
  <%end%>
</ul>

<a href="<%=user_url(current_user.id)%>">Up One Level</a>

app/views/bands/index.html.erb
<h1> All Bands </h1>

<ul>
  <% @bands.each do |band| %>
    <a href="<%=band_url(band.id)%>"><%=band.band_name%></a><br>
  <%end%>
</ul>

<br>

<a href="<%=user_url(@user.id)%>">Back to Profile</a>

app/views/bands/new.html.erb
<h1>Add a Band!!!!</h1>

<%=@band.errors.full_messages%>

<form action="<%=bands_url%>" method="POST">

  <label for="name"> Band Name</label>
  <input type="text" name="band[band_name]" id="name">
  <br>
  <button>Submit!</button>

</form>

<br>

<a href="<%=user_url(current_user.id)%>">Back</a>

app/views/bands/show.html.erb
<h1> Band name: <%=@band.band_name%> </h1>

Albums: <br>

<ul>

  <% @band.albums.each do |album| %>
    <a href="<%=album_url(album.id)%>"><%=album.title%></a><br>
  <%end%>

</ul>

<a href="<%=user_url(current_user.id)%>">Up One Level</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>

  <% if logged_in? %>
    <form action="<%=session_url%>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <button>Log out</button>
    </form>
  <%else%>
  <form action="<%=new_user_url%>" method="GET">
    <button>Create New User</button>
  </form>
  <form action="<%=new_session_url%>" method="GET">
    <button>Log In Page</button>
  </form>
  <%end%>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_post.html.erb
Post a comment!<br>
<form action="<%=track_notes_url(params[:id])%>" method="POST">
    Comment<br>
    <textarea name="note[body]"></textarea>
    <button>Post</button>
</form>

app/views/tracks/edit.html.erb
<form action="<%=track_url(@track.id)%>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <textarea name="track[lyrics]"><%=@track.lyrics%></textarea>
  <button>Submit!</button>
</form>

<a href="<%=track_url(@track.id)%>">Back to Previous Page</a>

app/views/tracks/new.html.erb
<h1>Add an Track!!!!</h1>

<%=@track.errors.full_messages if @track%>

<form action="<%=tracks_url%>" method="POST">

  <label for="name"> Song Name</label>
  <input type="text" name="track[song_name]" id="name">
  <br>
  Choose Band:
  <select name="track[album_id]">

    <% @albums.each do |album| %>
      <option value="<%=album.id%>"><%=album.title%></option>
    <%end%>

  </select>

  <button>Submit!</button>

</form>

<br>

<a href="<%=user_url(current_user.id)%>">Back</a>

app/views/tracks/show.html.erb
<h1>Song name: <%=@track.song_name%></h1>

Lyrics:<br>
<%=@track.lyrics if @track.lyrics %>
<br>
<a href="<%=edit_track_url(@track.id)%>">Edit Lyrics</a>
<ul>
  <% @track.notes.each do |note| %>

    <li> <b><%=note.author.email%>:</b> <br> <%=note.body%><br> </li>

    <% if note.user_id == @user.id%>

      <form action="<%=note_url(note.id)%>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <button>Delete Post</button>
      </form>

    <%end%>

  <%end%>
</ul>

<br>
<%= render "notes/post" %>
<br>
<a href="<%=album_url(@track.album_id)%>"> Up One Level </a>

app/views/users/index.html.erb
<% if logged_in? %>
  <a href="<%=user_url(@current.id) if @current%>">Go to My Profile</a>
<%end%>
<h1> Welcome to Eric's Pointless Music App! </h1>

<img src="http://images.clipartpanda.com/christmas-music-notes-border-singing_8355-1.jpg" width=800
  height=400>
<br>
members:
<br>
  <% @users.each do |user| %>
  <a href="<%= user_url(user.id)%>"><%=user.email%></a>
  <br>
  <%end%>

app/views/users/new.html.erb
<h1>This is the sign up form</h1>

<%=@user.errors.full_messages%>

<form action="<%=users_url%>" method="POST">

  <label for="email"> Email</label>
  <input type="text" name="user[email]" id="email">
  <br>

  <label for="password"> Password</label>
  <input type="password" name="user[password]" id="password">
  <br>

  <button>Make User!</button>

</form>

<br>

<a href="/users">Back to Homepage</a>

app/views/users/show.html.erb
<h1>This is your profile page </h1>

Your email is:  <%= @user.email %>

<br>

<a href="/bands">View Bands</a>

<br>

<a href="<%=new_band_url%>"> Add a Band!</a>

<br>

<a href="<%=new_album_url%>"> Add an Album!!</a>

<br>

<a href="<%=new_track_url%>"> Add Track!!</a>

<br>

<a href="/users">Back to Homepage</a>